services:
  api:
    build: .
    environment:
      - PORT=3000
      - MYSQL_HOST=db
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

      - MINIO_ENDPOINT=minio
      - MINIO_PORT
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    ports:
      - $PORT:3000
    depends_on:
      - db
      - minio

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - .data/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=$MINIO_ACCESS_KEY
      - MINIO_ROOT_PASSWORD=$MINIO_SECRET_KEY
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - .data/minio:/data
    command: server /data --console-address ":9001"

  cubejs:
    image: cubejs/cube:latest
    environment:
      - CUBEJS_DB_HOST=db
      - CUBEJS_DB_NAME=$MYSQL_DATABASE
      - CUBEJS_DB_USER=$MYSQL_USER
      - CUBEJS_DB_PASS=$MYSQL_PASSWORD
      - CUBEJS_DB_TYPE=mysql
      - CUBEJS_API_SECRET=hello
      - CUBEJS_DEV_MODE=true
    depends_on:
      - db
    ports:
      - 3001:3000
      - 4000:4000
    volumes: 
      - ./cube/conf:/cube/conf
    