services:
  api:
    build: .
    environment:
      - PORT=3000
      - MYSQL_HOST=db
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - $PORT:3000
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - .data/mysql:/var/lib/mysql
