export enum DependantRelationship {
  Child = 'Child',
  HouseHelper = 'House Helper',
  Relative = 'Relative',
  Parent = 'Parent',
  Sibling = 'Sibling',
  Grandchild = 'Grandchild',
  Grandparent = 'Grandparent',
  NieceNephew = 'Niece/Nephew',
  Guardian = 'Guardian',
  Ward = 'Ward',
  Spouse = 'Spouse',
  InLaw = 'In-Law',
  ExtendedFamily = 'Extended Family',
  Other = 'Other',
}
